const _ = require('lodash'),

  /**
   * Sentinel written as the first line of every auto-generated contract-test script. Downstream
   * consumers (e.g. api-specification-service's spec <> collection sync) match on this marker to
   * identify and refresh the generated event without touching user-authored test scripts. Keep this
   * string stable — changing it is a breaking change for those consumers.
   */
  CONTRACT_TEST_MARKER = '// @postman-contract-test v1 (auto-generated by openapi-to-postman)',

  APP_JSON = 'application/json',

  /**
   * `resolveFor` value passed to schemaUtils.resolveSchema when building the JSON Schema embedded in
   * the assertion. Deliberately NOT 'conversion'/'typesGeneration': those modes are tuned for example
   * generation — they collapse `oneOf`/`anyOf` to the first subschema and inject faker `default`
   * placeholders (e.g. "<string>"). For a validation schema we want the structural form preserved and
   * unpolluted, which is exactly what any non-conversion `resolveFor` yields.
   */
  RESOLVE_FOR_VALIDATION = 'validation',

  /**
   * Picks the JSON body schema out of an OpenAPI `content` object, preferring `application/json`
   * and falling back to any `*+json` / json-family media type.
   *
   * @param {Object} content - OpenAPI media-type map (responseObject.content)
   * @returns {Object|undefined} the schema for the JSON media type, if any
   */
  pickJsonSchema = (content) => {
    if (!_.isObject(content)) {
      return undefined;
    }

    if (_.get(content, [APP_JSON, 'schema'])) {
      return content[APP_JSON].schema;
    }

    const jsonKey = _.find(Object.keys(content), (mediaType) => {
      return (/[/+]json(;|$)/i).test(mediaType);
    });

    return jsonKey ? _.get(content, [jsonKey, 'schema']) : undefined;
  },

  /**
   * Builds the `pm.test` script body (as an `exec` string array) for a single operation's contract
   * test. The generated script asserts (a) the response status code is one declared in the spec and
   * (b) the response body validates against the declared response schema for that status.
   *
   * @param {number[]} declaredCodes - explicit numeric status codes declared in the spec
   * @param {Object} schemasByStatus - map of status-code (string) | 'default' -> resolved JSON schema
   * @param {boolean} hasDefaultResponse - whether the spec declares a `default` response
   * @returns {string[]} the script `exec` lines
   */
  buildExec = (declaredCodes, schemasByStatus, hasDefaultResponse) => {
    return [
      CONTRACT_TEST_MARKER,
      '// Auto-generated contract test. Regenerated when the collection is synced with its API spec;',
      '// manual edits to this script may be overwritten.',
      'var declaredStatusCodes = ' + JSON.stringify(declaredCodes) + ';',
      'var responseSchemas = ' + JSON.stringify(schemasByStatus) + ';',
      'var specHasDefaultResponse = ' + JSON.stringify(Boolean(hasDefaultResponse)) + ';',
      '',
      '// A `default` response in OpenAPI matches any status code, so only assert membership when',
      '// the spec does not declare one.',
      'if (!specHasDefaultResponse) {',
      '  pm.test(\'Contract | Status code is declared in the API specification\', function () {',
      '    pm.expect(declaredStatusCodes).to.include(pm.response.code);',
      '  });',
      '}',
      '',
      'var schemaForStatus = responseSchemas[String(pm.response.code)] || responseSchemas.default;',
      'if (schemaForStatus) {',
      '  pm.test(\'Contract | Response body matches the schema for status \' + pm.response.code, function () {',
      '    pm.response.to.have.jsonSchema(schemaForStatus);',
      '  });',
      '}'
    ];
  },

  /**
   * Builds the contract-test event for a single OpenAPI operation.
   *
   * @param {Object} context - conversion context (carries computedOptions, schema caches, openapi)
   * @param {Object} operationItem - the path item (operationItem[method] is the operation object)
   * @param {String} method - HTTP method (lowercase)
   * @param {Object} helpers - injected resolver(s) from schemaUtils to avoid a circular require
   * @param {Function} helpers.resolveSchema - schemaUtils.resolveSchema, used to inline $refs
   * @returns {Array} an Item `event` array (empty when there is nothing to assert)
   */
  buildContractTestEvent = (context, operationItem, method, helpers) => {
    const resolveSchema = _.get(helpers, 'resolveSchema'),
      operation = _.get(operationItem, method),
      responses = _.get(operation, 'responses');

    if (!_.isObject(responses) || !_.isFunction(resolveSchema)) {
      return [];
    }

    const declaredCodes = [],
      schemasByStatus = {};

    let hasDefaultResponse = false;

    _.forOwn(responses, (responseObject, code) => {
      let resolvedResponse = responseObject;

      try {
        if (_.has(responseObject, '$ref')) {
          resolvedResponse = resolveSchema(context, responseObject,
            { isResponseSchema: true, resolveFor: RESOLVE_FOR_VALIDATION });
        }
      }
      catch (e) {
        // If the response object itself can't be resolved, skip it rather than fail the conversion.
        return;
      }

      // Normalize the status code: `2XX`/`5xx` -> `200`/`500`; `default` is a catch-all.
      let statusKey;

      if (code === 'default') {
        hasDefaultResponse = true;
        statusKey = 'default';
      }
      else if ((/^\d/).test(code)) {
        const numericCode = _.toSafeInteger(String(code).replace(/[xX]/g, '0'));

        declaredCodes.push(numericCode);
        statusKey = String(numericCode);
      }
      else {
        return;
      }

      const bodySchema = pickJsonSchema(_.get(resolvedResponse, 'content'));

      if (bodySchema) {
        try {
          schemasByStatus[statusKey] = resolveSchema(context, bodySchema,
            { isResponseSchema: true, resolveFor: RESOLVE_FOR_VALIDATION });
        }
        catch (e) {
          // Skip an unresolvable body schema; the status-code assertion is still emitted.
        }
      }
    });

    if (declaredCodes.length === 0 && !hasDefaultResponse) {
      return [];
    }

    return [{
      listen: 'test',
      script: {
        type: 'text/javascript',
        exec: buildExec(declaredCodes, schemasByStatus, hasDefaultResponse)
      }
    }];
  };

module.exports = {
  CONTRACT_TEST_MARKER,
  buildContractTestEvent
};
