const _ = require('lodash'),

  /**
   * Sentinel written as the first line of every auto-generated contract-test script. Downstream
   * consumers (e.g. api-specification-service's spec <> collection sync) match on this marker to
   * identify and refresh the generated event without touching user-authored test scripts. Keep this
   * string stable — changing it is a breaking change for those consumers.
   */
  CONTRACT_TEST_MARKER = '// @postman-contract-test v1 (auto-generated by openapi-to-postman)',

  APP_JSON = 'application/json',

  /**
   * `resolveFor` value passed to schemaUtils.resolveSchema when building the JSON Schema embedded in
   * the assertion. Deliberately NOT 'conversion'/'typesGeneration': those modes are tuned for example
   * generation — they collapse `oneOf`/`anyOf` to the first subschema and inject faker `default`
   * placeholders (e.g. "<string>"). For a validation schema we want the structural form preserved and
   * unpolluted, which is exactly what any non-conversion `resolveFor` yields.
   */
  RESOLVE_FOR_VALIDATION = 'validation',

  /**
   * OpenAPI vendor extension that declares request-chaining bindings (contract-test feature).
   * `save` (on a response object) captures a value from the response into a collection variable;
   * `load` (on a parameter object) injects a previously-saved variable as `{{name}}` into the request.
   */
  X_POSTMAN_VARIABLES = 'x-postman-variables',

  /**
   * Normalizes a save `path` into a lodash property path for `_.get`. A leading `$`/`$.` (JSONPath
   * habit) is stripped; the remainder is used verbatim. This is member-access + numeric-index only —
   * NOT a JSONPath evaluator, so wildcards/filters/recursive-descent are unsupported.
   *
   * @param {String} path - the declared path (e.g. `$.data[0].id`)
   * @returns {String} a lodash path (e.g. `data[0].id`)
   */
  normalizeLodashPath = (path) => {
    if (typeof path !== 'string') {
      return '';
    }

    return path.replace(/^\$\.?/, '');
  },

  /**
   * Reads `x-postman-variables` entries of a given `type` off a spec node, tolerating either a single
   * object or an array. Returns the raw matching entries (unnormalized).
   *
   * @param {Object} node - a spec node (response object or parameter object)
   * @param {String} type - `save` | `load`
   * @returns {Object[]} matching binding entries
   */
  readVariableBindings = (node, type) => {
    const raw = _.get(node, [X_POSTMAN_VARIABLES]),
      list = _.isArray(raw) ? raw : (_.isObject(raw) ? [raw] : []);

    return list.filter((binding) => {
      return _.isObject(binding) && binding.type === type &&
        typeof binding.name === 'string' && binding.name.length > 0;
    });
  },

  /**
   * Normalized `save` bindings declared on a response object. Each becomes a runtime capture into a
   * collection variable: from the JSON body (`_.get(body, path)`) or a named response header.
   *
   * @param {Object} responseObject - an OpenAPI response object
   * @returns {Object[]} normalized save bindings, each `{ name, source, path | header }`
   */
  getSaveBindings = (responseObject) => {
    return readVariableBindings(responseObject, 'save')
      .map((binding) => {
        if (binding.from === 'header') {
          return { name: binding.name, source: 'header', header: binding.header };
        }

        return { name: binding.name, source: 'body', path: normalizeLodashPath(binding.path || '') };
      })
      .filter((binding) => {
        // A header save needs a header name; a body save is always usable (empty path reads the root).
        return binding.source === 'header' ?
          (typeof binding.header === 'string' && binding.header.length > 0) : true;
      });
  },

  /**
   * The single `load` binding declared on a parameter object, if any (first wins).
   *
   * @param {Object} param - an OpenAPI parameter object
   * @returns {Object|null} the load binding `{ name }`, or null when none is declared
   */
  getLoadBinding = (param) => {
    const load = readVariableBindings(param, 'load')[0];

    return load ? { name: load.name } : null;
  },

  /**
   * Picks the JSON body schema out of an OpenAPI `content` object, preferring `application/json`
   * and falling back to any `*+json` / json-family media type.
   *
   * @param {Object} content - OpenAPI media-type map (responseObject.content)
   * @returns {Object|undefined} the schema for the JSON media type, if any
   */
  pickJsonSchema = (content) => {
    if (!_.isObject(content)) {
      return undefined;
    }

    if (_.get(content, [APP_JSON, 'schema'])) {
      return content[APP_JSON].schema;
    }

    const jsonKey = _.find(Object.keys(content), (mediaType) => {
      return (/[/+]json(;|$)/i).test(mediaType);
    });

    return jsonKey ? _.get(content, [jsonKey, 'schema']) : undefined;
  },

  /**
   * JSON Schema draft-07 standard `format` values. The Postman/Newman runtime validates the embedded
   * schema with Ajv 6 (default `unknownFormats: true`), which THROWS at compile time on any other
   * `format` — so OpenAPI's non-standard formats (`int64`, `byte`, `binary`, `password`, ...) must be
   * dropped. Keeping only these standard formats preserves meaningful validation without the throw, and
   * is validator-agnostic (also fine under a future Ajv 7/8).
   */
  STANDARD_JSON_SCHEMA_FORMATS = new Set([
    'date-time', 'date', 'time', 'duration', 'email', 'idn-email', 'hostname', 'idn-hostname',
    'ipv4', 'ipv6', 'uri', 'uri-reference', 'iri', 'iri-reference', 'uri-template', 'json-pointer',
    'relative-json-pointer', 'regex', 'uuid'
  ]),

  /**
   * OpenAPI-only keywords that are NOT part of JSON Schema. They are meaningless to (and silently
   * ignored by) the runtime validator, so strip them to keep the embedded schema clean. NOTE: `examples`
   * (plural) is deliberately NOT here — it IS a valid JSON Schema annotation (draft-06+). `default` is
   * also stripped (annotation-only; the converter can inject `"<string>"` placeholders).
   */
  OPENAPI_ONLY_KEYWORDS = ['default', 'discriminator', 'xml', 'externalDocs', 'example', 'deprecated'],

  /**
   * Rewrites an OpenAPI `nullable: true` node into standard JSON Schema nullability (in place). Assumes
   * `nullable` has already been read; callers delete the keyword separately.
   *
   * @param {Object} node - a schema object that was marked `nullable: true`
   * @returns {void}
   */
  applyNullable = (node) => {
    if (typeof node.type === 'string') {
      if (node.type !== 'null') {
        node.type = [node.type, 'null'];
      }
    }
    else if (_.isArray(node.type)) {
      if (!node.type.includes('null')) {
        node.type.push('null');
      }
    }
    else {
      // No `type` to extend (e.g. a bare composite / enum). Wrap the whole node in an anyOf that also
      // permits null. Move the node's own keys into an inner copy, then replace them with the wrapper.
      const inner = {};

      Object.keys(node).forEach((key) => {
        inner[key] = node[key];
        delete node[key];
      });

      node.anyOf = [inner, { type: 'null' }];
    }
  },

  /**
   * Recursively rewrites a resolved OpenAPI schema into portable JSON Schema so the embedded contract
   * assertion validates correctly under the Postman sandbox's Ajv 6 (and any other validator):
   *   - `nullable: true` -> standard nullability (`type: [.., 'null']` or an `anyOf` with `{type:'null'}`)
   *   - OpenAPI-only annotation keywords removed (see OPENAPI_ONLY_KEYWORDS)
   *   - non-standard `format` values dropped (see STANDARD_JSON_SCHEMA_FORMATS)
   *
   * Recurses ONLY into real schema positions (never a blind key walk) so that user schemas with a
   * property literally named `example`/`format`/`default` are not corrupted. Mutates in place.
   *
   * @param {*} node - a schema (sub)tree
   * @returns {*} the same node, mutated in place
   */
  sanitizeContractSchema = (node) => {
    if (_.isArray(node)) {
      node.forEach(sanitizeContractSchema);

      return node;
    }

    if (!_.isObject(node)) {
      return node;
    }

    const isNullable = node.nullable === true;

    OPENAPI_ONLY_KEYWORDS.forEach((keyword) => {
      delete node[keyword];
    });

    delete node.nullable;

    if (typeof node.format === 'string' && !STANDARD_JSON_SCHEMA_FORMATS.has(node.format)) {
      delete node.format;
    }

    // Recurse into schema-bearing positions only.
    if (_.isObject(node.properties)) {
      Object.keys(node.properties).forEach((key) => {
        return sanitizeContractSchema(node.properties[key]);
      });
    }

    if (_.isObject(node.patternProperties)) {
      Object.keys(node.patternProperties).forEach((key) => {
        return sanitizeContractSchema(node.patternProperties[key]);
      });
    }

    if (_.isObject(node.additionalProperties)) {
      sanitizeContractSchema(node.additionalProperties);
    }

    // `items` / `additionalItems` may be a single schema or an array of schemas.
    if (_.isObject(node.items)) {
      sanitizeContractSchema(node.items);
    }

    if (_.isObject(node.additionalItems)) {
      sanitizeContractSchema(node.additionalItems);
    }

    ['allOf', 'anyOf', 'oneOf'].forEach((keyword) => {
      if (_.isArray(node[keyword])) {
        node[keyword].forEach(sanitizeContractSchema);
      }
    });

    if (_.isObject(node.not)) {
      sanitizeContractSchema(node.not);
    }

    // Apply nullability last, after children are sanitized (the wrap case restructures this node).
    if (isNullable) {
      applyNullable(node);
    }

    return node;
  },

  /**
   * Builds the `pm.test` script body (as an `exec` string array) for a single operation's contract
   * test. The generated script asserts (a) the response status code is one declared in the spec and
   * (b) the response body validates against the declared response schema for that status.
   *
   * @param {number[]} declaredCodes - explicit numeric status codes declared in the spec
   * @param {Object} schemasByStatus - map of status-code (string) | 'default' -> resolved JSON schema
   * @param {boolean} hasDefaultResponse - whether the spec declares a `default` response
   * @returns {string[]} the script `exec` lines
   */
  buildExec = (declaredCodes, schemasByStatus, hasDefaultResponse) => {
    return [
      CONTRACT_TEST_MARKER,
      '// Auto-generated contract test. Regenerated when the collection is synced with its API spec;',
      '// manual edits to this script may be overwritten.',
      'var declaredStatusCodes = ' + JSON.stringify(declaredCodes) + ';',
      'var responseSchemas = ' + JSON.stringify(schemasByStatus) + ';',
      'var specHasDefaultResponse = ' + JSON.stringify(Boolean(hasDefaultResponse)) + ';',
      '',
      '// A `default` response in OpenAPI matches any status code, so only assert membership when',
      '// the spec does not declare one.',
      'if (!specHasDefaultResponse) {',
      '  pm.test(\'Contract | Status code is declared in the API specification\', function () {',
      '    pm.expect(declaredStatusCodes).to.include(pm.response.code);',
      '  });',
      '}',
      '',
      'var schemaForStatus = responseSchemas[String(pm.response.code)] || responseSchemas.default;',
      'if (schemaForStatus) {',
      '  pm.test(\'Contract | Response body matches the schema for status \' + pm.response.code, function () {',
      '    pm.response.to.have.jsonSchema(schemaForStatus);',
      '  });',
      '}'
    ];
  },

  /**
   * Builds the runtime save-block appended to the contract-test script: for the matched response
   * status it captures each declared value into a collection variable (so a later request can reuse
   * it) and asserts the value was present. Emitted only when the operation declares `save` bindings.
   *
   * @param {Object} savesByStatus - map of status-code (string) | 'default' -> normalized save bindings
   * @returns {String[]} the script `exec` lines
   */
  buildSaveBlock = (savesByStatus) => {
    return [
      '',
      '// Request chaining: capture declared values from the response into collection variables so a',
      '// later request can reuse them (e.g. an id from a create response used as a path parameter).',
      'var contractSavesByStatus = ' + JSON.stringify(savesByStatus) + ';',
      'var contractSaves = contractSavesByStatus[String(pm.response.code)] || contractSavesByStatus.default || [];',
      'if (contractSaves.length) {',
      '  var contractLodash = require(\'lodash\');',
      '  var contractBody;',
      '  try { contractBody = pm.response.json(); } catch (e) { contractBody = undefined; }',
      '  contractSaves.forEach(function (binding) {',
      '    var value = binding.source === \'header\' ?',
      '      pm.response.headers.get(binding.header) : contractLodash.get(contractBody, binding.path);',
      '    pm.test("Contract | Saved \'" + binding.name + "\' from response", function () {',
      '      pm.expect(value, binding.name + \' not found in response\').to.not.be.undefined;',
      '    });',
      '    if (typeof value !== \'undefined\' && value !== null) {',
      '      pm.collectionVariables.set(binding.name, value);',
      '    }',
      '  });',
      '}'
    ];
  },

  /**
   * Builds the contract-test event for a single OpenAPI operation.
   *
   * @param {Object} context - conversion context (carries computedOptions, schema caches, openapi)
   * @param {Object} operationItem - the path item (operationItem[method] is the operation object)
   * @param {String} method - HTTP method (lowercase)
   * @param {Object} helpers - injected resolver(s) from schemaUtils to avoid a circular require
   * @param {Function} helpers.resolveSchema - schemaUtils.resolveSchema, used to inline $refs
   * @returns {Array} an Item `event` array (empty when there is nothing to assert)
   */
  buildContractTestEvent = (context, operationItem, method, helpers) => {
    const resolveSchema = _.get(helpers, 'resolveSchema'),
      operation = _.get(operationItem, method),
      responses = _.get(operation, 'responses');

    if (!_.isObject(responses) || !_.isFunction(resolveSchema)) {
      return [];
    }

    const declaredCodes = [],
      schemasByStatus = {},
      savesByStatus = {};

    let hasDefaultResponse = false,
      hasSaves = false;

    _.forOwn(responses, (responseObject, code) => {
      let resolvedResponse = responseObject;

      try {
        if (_.has(responseObject, '$ref')) {
          resolvedResponse = resolveSchema(context, responseObject,
            { isResponseSchema: true, resolveFor: RESOLVE_FOR_VALIDATION });
        }
      }
      catch (e) {
        // If the response object itself can't be resolved, skip it rather than fail the conversion.
        return;
      }

      // Normalize the status code: `2XX`/`5xx` -> `200`/`500`; `default` is a catch-all.
      let statusKey;

      if (code === 'default') {
        hasDefaultResponse = true;
        statusKey = 'default';
      }
      else if ((/^\d/).test(code)) {
        const numericCode = _.toSafeInteger(String(code).replace(/[xX]/g, '0'));

        declaredCodes.push(numericCode);
        statusKey = String(numericCode);
      }
      else {
        return;
      }

      // Request-chaining `save` bindings declared on this response: capture into collection variables
      // at runtime, keyed by the response status so we only save when that status actually occurs.
      const saveBindings = getSaveBindings(resolvedResponse);

      if (saveBindings.length) {
        savesByStatus[statusKey] = saveBindings;
        hasSaves = true;
      }

      const bodySchema = pickJsonSchema(_.get(resolvedResponse, 'content'));

      if (bodySchema) {
        try {
          const resolved = resolveSchema(context, bodySchema,
            { isResponseSchema: true, resolveFor: RESOLVE_FOR_VALIDATION });

          schemasByStatus[statusKey] = sanitizeContractSchema(_.cloneDeep(resolved));
        }
        catch (e) {
          // Skip an unresolvable body schema; the status-code assertion is still emitted.
        }
      }
    });

    if (declaredCodes.length === 0 && !hasDefaultResponse && !hasSaves) {
      return [];
    }

    const exec = buildExec(declaredCodes, schemasByStatus, hasDefaultResponse);

    if (hasSaves) {
      exec.push(...buildSaveBlock(savesByStatus));
    }

    return [{
      listen: 'test',
      script: {
        type: 'text/javascript',
        exec
      }
    }];
  };

module.exports = {
  CONTRACT_TEST_MARKER,
  X_POSTMAN_VARIABLES,
  buildContractTestEvent,
  getSaveBindings,
  getLoadBinding,
  normalizeLodashPath
};
